<?xml version='1.0'?>
<package format='2'>
  <name>hpp_python</name>
  <version>9.0.2</version>
  <description>Implement python bindings for HPP</description>
  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>BSD-2-Clause</license>

  <depend>eigenpy</depend>
  <depend>pinocchio</depend>
  <depend>hpp_util</depend>
  <depend>hpp_pinocchio</depend>
  <depend>hpp_constraints</depend>
  <depend>hpp_core</depend>
  <depend>hpp_manipulation</depend>
  <depend>hpp_manipulation_urdf</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>doxygen</build_depend>
  <build_depend>jrl_cmakemodules</build_depend>
  <build_depend>python3-lxml</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
